use hrms;
CREATE TABLE trade_manpower_daily (
    -- Primary Key
    id INT PRIMARY KEY AUTO_INCREMENT,
    
    -- Date (unique per day)
    report_date DATE NOT NULL UNIQUE,
    
    -- ==================== OP CIPH (Trade 1) ====================
    op_ciph_auth INT DEFAULT 0,
    op_ciph_hs INT DEFAULT 0,
    op_ciph_held INT DEFAULT 0,
    op_ciph_av INT DEFAULT 0,
    op_ciph_dist_hq INT DEFAULT 0,
    op_ciph_dist_1 INT DEFAULT 0,
    op_ciph_dist_2 INT DEFAULT 0,
    op_ciph_dist_3 INT DEFAULT 0,
    op_ciph_state_hq INT DEFAULT 0,
    op_ciph_state_1 INT DEFAULT 0,
    op_ciph_state_2 INT DEFAULT 0,
    op_ciph_state_3 INT DEFAULT 0,
    op_ciph_present_hq INT DEFAULT 0,
    op_ciph_present_1 INT DEFAULT 0,
    op_ciph_present_2 INT DEFAULT 0,
    op_ciph_present_3 INT DEFAULT 0,
    
    -- ==================== OSS (Trade 2) ====================
    oss_auth INT DEFAULT 0,
    oss_hs INT DEFAULT 0,
    oss_held INT DEFAULT 0,
    oss_av INT DEFAULT 0,
    oss_dist_hq INT DEFAULT 0,
    oss_dist_1 INT DEFAULT 0,
    oss_dist_2 INT DEFAULT 0,
    oss_dist_3 INT DEFAULT 0,
    oss_state_hq INT DEFAULT 0,
    oss_state_1 INT DEFAULT 0,
    oss_state_2 INT DEFAULT 0,
    oss_state_3 INT DEFAULT 0,
    oss_present_hq INT DEFAULT 0,
    oss_present_1 INT DEFAULT 0,
    oss_present_2 INT DEFAULT 0,
    oss_present_3 INT DEFAULT 0,
    
    -- ==================== OCC (Trade 3) ====================
    occ_auth INT DEFAULT 0,
    occ_hs INT DEFAULT 0,
    occ_held INT DEFAULT 0,
    occ_av INT DEFAULT 0,
    occ_dist_hq INT DEFAULT 0,
    occ_dist_1 INT DEFAULT 0,
    occ_dist_2 INT DEFAULT 0,
    occ_dist_3 INT DEFAULT 0,
    occ_state_hq INT DEFAULT 0,
    occ_state_1 INT DEFAULT 0,
    occ_state_2 INT DEFAULT 0,
    occ_state_3 INT DEFAULT 0,
    occ_present_hq INT DEFAULT 0,
    occ_present_1 INT DEFAULT 0,
    occ_present_2 INT DEFAULT 0,
    occ_present_3 INT DEFAULT 0,
    
    -- ==================== TTC (Trade 4) ====================
    ttc_auth INT DEFAULT 0,
    ttc_hs INT DEFAULT 0,
    ttc_held INT DEFAULT 0,
    ttc_av INT DEFAULT 0,
    ttc_dist_hq INT DEFAULT 0,
    ttc_dist_1 INT DEFAULT 0,
    ttc_dist_2 INT DEFAULT 0,
    ttc_dist_3 INT DEFAULT 0,
    ttc_state_hq INT DEFAULT 0,
    ttc_state_1 INT DEFAULT 0,
    ttc_state_2 INT DEFAULT 0,
    ttc_state_3 INT DEFAULT 0,
    ttc_present_hq INT DEFAULT 0,
    ttc_present_1 INT DEFAULT 0,
    ttc_present_2 INT DEFAULT 0,
    ttc_present_3 INT DEFAULT 0,
    
    -- ==================== LMN (Trade 5) ====================
    lmn_auth INT DEFAULT 0,
    lmn_hs INT DEFAULT 0,
    lmn_held INT DEFAULT 0,
    lmn_av INT DEFAULT 0,
    lmn_dist_hq INT DEFAULT 0,
    lmn_dist_1 INT DEFAULT 0,
    lmn_dist_2 INT DEFAULT 0,
    lmn_dist_3 INT DEFAULT 0,
    lmn_state_hq INT DEFAULT 0,
    lmn_state_1 INT DEFAULT 0,
    lmn_state_2 INT DEFAULT 0,
    lmn_state_3 INT DEFAULT 0,
    lmn_present_hq INT DEFAULT 0,
    lmn_present_1 INT DEFAULT 0,
    lmn_present_2 INT DEFAULT 0,
    lmn_present_3 INT DEFAULT 0,
    
    -- ==================== EFS (Trade 6) ====================
    efs_auth INT DEFAULT 0,
    efs_hs INT DEFAULT 0,
    efs_held INT DEFAULT 0,
    efs_av INT DEFAULT 0,
    efs_dist_hq INT DEFAULT 0,
    efs_dist_1 INT DEFAULT 0,
    efs_dist_2 INT DEFAULT 0,
    efs_dist_3 INT DEFAULT 0,
    efs_state_hq INT DEFAULT 0,
    efs_state_1 INT DEFAULT 0,
    efs_state_2 INT DEFAULT 0,
    efs_state_3 INT DEFAULT 0,
    efs_present_hq INT DEFAULT 0,
    efs_present_1 INT DEFAULT 0,
    efs_present_2 INT DEFAULT 0,
    efs_present_3 INT DEFAULT 0,
    
    -- ==================== DVR MT (Trade 7) ====================
    dvr_mt_auth INT DEFAULT 0,
    dvr_mt_hs INT DEFAULT 0,
    dvr_mt_held INT DEFAULT 0,
    dvr_mt_av INT DEFAULT 0,
    dvr_mt_dist_hq INT DEFAULT 0,
    dvr_mt_dist_1 INT DEFAULT 0,
    dvr_mt_dist_2 INT DEFAULT 0,
    dvr_mt_dist_3 INT DEFAULT 0,
    dvr_mt_state_hq INT DEFAULT 0,
    dvr_mt_state_1 INT DEFAULT 0,
    dvr_mt_state_2 INT DEFAULT 0,
    dvr_mt_state_3 INT DEFAULT 0,
    dvr_mt_present_hq INT DEFAULT 0,
    dvr_mt_present_1 INT DEFAULT 0,
    dvr_mt_present_2 INT DEFAULT 0,
    dvr_mt_present_3 INT DEFAULT 0,
    
    -- ==================== DR (Trade 8) ====================
    dr_auth INT DEFAULT 0,
    dr_hs INT DEFAULT 0,
    dr_held INT DEFAULT 0,
    dr_av INT DEFAULT 0,
    dr_dist_hq INT DEFAULT 0,
    dr_dist_1 INT DEFAULT 0,
    dr_dist_2 INT DEFAULT 0,
    dr_dist_3 INT DEFAULT 0,
    dr_state_hq INT DEFAULT 0,
    dr_state_1 INT DEFAULT 0,
    dr_state_2 INT DEFAULT 0,
    dr_state_3 INT DEFAULT 0,
    dr_present_hq INT DEFAULT 0,
    dr_present_1 INT DEFAULT 0,
    dr_present_2 INT DEFAULT 0,
    dr_present_3 INT DEFAULT 0,
    
    -- ==================== DTMN (Trade 9) ====================
    dtmn_auth INT DEFAULT 0,
    dtmn_hs INT DEFAULT 0,
    dtmn_held INT DEFAULT 0,
    dtmn_av INT DEFAULT 0,
    dtmn_dist_hq INT DEFAULT 0,
    dtmn_dist_1 INT DEFAULT 0,
    dtmn_dist_2 INT DEFAULT 0,
    dtmn_dist_3 INT DEFAULT 0,
    dtmn_state_hq INT DEFAULT 0,
    dtmn_state_1 INT DEFAULT 0,
    dtmn_state_2 INT DEFAULT 0,
    dtmn_state_3 INT DEFAULT 0,
    dtmn_present_hq INT DEFAULT 0,
    dtmn_present_1 INT DEFAULT 0,
    dtmn_present_2 INT DEFAULT 0,
    dtmn_present_3 INT DEFAULT 0,
    
    -- ==================== SKT (Trade 10) ====================
    skt_auth INT DEFAULT 0,
    skt_hs INT DEFAULT 0,
    skt_held INT DEFAULT 0,
    skt_av INT DEFAULT 0,
    skt_dist_hq INT DEFAULT 0,
    skt_dist_1 INT DEFAULT 0,
    skt_dist_2 INT DEFAULT 0,
    skt_dist_3 INT DEFAULT 0,
    skt_state_hq INT DEFAULT 0,
    skt_state_1 INT DEFAULT 0,
    skt_state_2 INT DEFAULT 0,
    skt_state_3 INT DEFAULT 0,
    skt_present_hq INT DEFAULT 0,
    skt_present_1 INT DEFAULT 0,
    skt_present_2 INT DEFAULT 0,
    skt_present_3 INT DEFAULT 0,
    
    -- ==================== ARTSN (Trade 11) ====================
    artsn_auth INT DEFAULT 0,
    artsn_hs INT DEFAULT 0,
    artsn_held INT DEFAULT 0,
    artsn_av INT DEFAULT 0,
    artsn_dist_hq INT DEFAULT 0,
    artsn_dist_1 INT DEFAULT 0,
    artsn_dist_2 INT DEFAULT 0,
    artsn_dist_3 INT DEFAULT 0,
    artsn_state_hq INT DEFAULT 0,
    artsn_state_1 INT DEFAULT 0,
    artsn_state_2 INT DEFAULT 0,
    artsn_state_3 INT DEFAULT 0,
    artsn_present_hq INT DEFAULT 0,
    artsn_present_1 INT DEFAULT 0,
    artsn_present_2 INT DEFAULT 0,
    artsn_present_3 INT DEFAULT 0,
    
    -- ==================== W/MAN (Trade 12) ====================
    w_man_auth INT DEFAULT 0,
    w_man_hs INT DEFAULT 0,
    w_man_held INT DEFAULT 0,
    w_man_av INT DEFAULT 0,
    w_man_dist_hq INT DEFAULT 0,
    w_man_dist_1 INT DEFAULT 0,
    w_man_dist_2 INT DEFAULT 0,
    w_man_dist_3 INT DEFAULT 0,
    w_man_state_hq INT DEFAULT 0,
    w_man_state_1 INT DEFAULT 0,
    w_man_state_2 INT DEFAULT 0,
    w_man_state_3 INT DEFAULT 0,
    w_man_present_hq INT DEFAULT 0,
    w_man_present_1 INT DEFAULT 0,
    w_man_present_2 INT DEFAULT 0,
    w_man_present_3 INT DEFAULT 0,
    
    -- ==================== STEWARD (Trade 13) ====================
    steward_auth INT DEFAULT 0,
    steward_hs INT DEFAULT 0,
    steward_held INT DEFAULT 0,
    steward_av INT DEFAULT 0,
    steward_dist_hq INT DEFAULT 0,
    steward_dist_1 INT DEFAULT 0,
    steward_dist_2 INT DEFAULT 0,
    steward_dist_3 INT DEFAULT 0,
    steward_state_hq INT DEFAULT 0,
    steward_state_1 INT DEFAULT 0,
    steward_state_2 INT DEFAULT 0,
    steward_state_3 INT DEFAULT 0,
    steward_present_hq INT DEFAULT 0,
    steward_present_1 INT DEFAULT 0,
    steward_present_2 INT DEFAULT 0,
    steward_present_3 INT DEFAULT 0,
    
    -- ==================== DRESSER (Trade 14) ====================
    dresser_auth INT DEFAULT 0,
    dresser_hs INT DEFAULT 0,
    dresser_held INT DEFAULT 0,
    dresser_av INT DEFAULT 0,
    dresser_dist_hq INT DEFAULT 0,
    dresser_dist_1 INT DEFAULT 0,
    dresser_dist_2 INT DEFAULT 0,
    dresser_dist_3 INT DEFAULT 0,
    dresser_state_hq INT DEFAULT 0,
    dresser_state_1 INT DEFAULT 0,
    dresser_state_2 INT DEFAULT 0,
    dresser_state_3 INT DEFAULT 0,
    dresser_present_hq INT DEFAULT 0,
    dresser_present_1 INT DEFAULT 0,
    dresser_present_2 INT DEFAULT 0,
    dresser_present_3 INT DEFAULT 0,
    
    -- ==================== HKEEPER (Trade 15) ====================
    hkeeper_auth INT DEFAULT 0,
    hkeeper_hs INT DEFAULT 0,
    hkeeper_held INT DEFAULT 0,
    hkeeper_av INT DEFAULT 0,
    hkeeper_dist_hq INT DEFAULT 0,
    hkeeper_dist_1 INT DEFAULT 0,
    hkeeper_dist_2 INT DEFAULT 0,
    hkeeper_dist_3 INT DEFAULT 0,
    hkeeper_state_hq INT DEFAULT 0,
    hkeeper_state_1 INT DEFAULT 0,
    hkeeper_state_2 INT DEFAULT 0,
    hkeeper_state_3 INT DEFAULT 0,
    hkeeper_present_hq INT DEFAULT 0,
    hkeeper_present_1 INT DEFAULT 0,
    hkeeper_present_2 INT DEFAULT 0,
    hkeeper_present_3 INT DEFAULT 0,
    
    -- ==================== MKEEPER (Trade 16) ====================
    mkeeper_auth INT DEFAULT 0,
    mkeeper_hs INT DEFAULT 0,
    mkeeper_held INT DEFAULT 0,
    mkeeper_av INT DEFAULT 0,
    mkeeper_dist_hq INT DEFAULT 0,
    mkeeper_dist_1 INT DEFAULT 0,
    mkeeper_dist_2 INT DEFAULT 0,
    mkeeper_dist_3 INT DEFAULT 0,
    mkeeper_state_hq INT DEFAULT 0,
    mkeeper_state_1 INT DEFAULT 0,
    mkeeper_state_2 INT DEFAULT 0,
    mkeeper_state_3 INT DEFAULT 0,
    mkeeper_present_hq INT DEFAULT 0,
    mkeeper_present_1 INT DEFAULT 0,
    mkeeper_present_2 INT DEFAULT 0,
    mkeeper_present_3 INT DEFAULT 0,
    
    -- ==================== CHEF MESS (Trade 17) ====================
    chef_mess_auth INT DEFAULT 0,
    chef_mess_hs INT DEFAULT 0,
    chef_mess_held INT DEFAULT 0,
    chef_mess_av INT DEFAULT 0,
    chef_mess_dist_hq INT DEFAULT 0,
    chef_mess_dist_1 INT DEFAULT 0,
    chef_mess_dist_2 INT DEFAULT 0,
    chef_mess_dist_3 INT DEFAULT 0,
    chef_mess_state_hq INT DEFAULT 0,
    chef_mess_state_1 INT DEFAULT 0,
    chef_mess_state_2 INT DEFAULT 0,
    chef_mess_state_3 INT DEFAULT 0,
    chef_mess_present_hq INT DEFAULT 0,
    chef_mess_present_1 INT DEFAULT 0,
    chef_mess_present_2 INT DEFAULT 0,
    chef_mess_present_3 INT DEFAULT 0,
    
    -- ==================== CHEF COM (Trade 18) ====================
    chef_com_auth INT DEFAULT 0,
    chef_com_hs INT DEFAULT 0,
    chef_com_held INT DEFAULT 0,
    chef_com_av INT DEFAULT 0,
    chef_com_dist_hq INT DEFAULT 0,
    chef_com_dist_1 INT DEFAULT 0,
    chef_com_dist_2 INT DEFAULT 0,
    chef_com_dist_3 INT DEFAULT 0,
    chef_com_state_hq INT DEFAULT 0,
    chef_com_state_1 INT DEFAULT 0,
    chef_com_state_2 INT DEFAULT 0,
    chef_com_state_3 INT DEFAULT 0,
    chef_com_present_hq INT DEFAULT 0,
    chef_com_present_1 INT DEFAULT 0,
    chef_com_present_2 INT DEFAULT 0,
    chef_com_present_3 INT DEFAULT 0,
    
    -- ==================== ER (Trade 19) ====================
    er_auth INT DEFAULT 0,
    er_hs INT DEFAULT 0,
    er_held INT DEFAULT 0,
    er_av INT DEFAULT 0,
    er_dist_hq INT DEFAULT 0,
    er_dist_1 INT DEFAULT 0,
    er_dist_2 INT DEFAULT 0,
    er_dist_3 INT DEFAULT 0,
    er_state_hq INT DEFAULT 0,
    er_state_1 INT DEFAULT 0,
    er_state_2 INT DEFAULT 0,
    er_state_3 INT DEFAULT 0,
    er_present_hq INT DEFAULT 0,
    er_present_1 INT DEFAULT 0,
    er_present_2 INT DEFAULT 0,
    er_present_3 INT DEFAULT 0,
    
    -- ==================== TLR (Trade 20) ====================
    tlr_auth INT DEFAULT 0,
    tlr_hs INT DEFAULT 0,
    tlr_held INT DEFAULT 0,
    tlr_av INT DEFAULT 0,
    tlr_dist_hq INT DEFAULT 0,
    tlr_dist_1 INT DEFAULT 0,
    tlr_dist_2 INT DEFAULT 0,
    tlr_dist_3 INT DEFAULT 0,
    tlr_state_hq INT DEFAULT 0,
    tlr_state_1 INT DEFAULT 0,
    tlr_state_2 INT DEFAULT 0,
    tlr_state_3 INT DEFAULT 0,
    tlr_present_hq INT DEFAULT 0,
    tlr_present_1 INT DEFAULT 0,
    tlr_present_2 INT DEFAULT 0,
    tlr_present_3 INT DEFAULT 0,
    
    -- ==================== CLK SD (Trade 21) ====================
    clk_sd_auth INT DEFAULT 0,
    clk_sd_hs INT DEFAULT 0,
    clk_sd_held INT DEFAULT 0,
    clk_sd_av INT DEFAULT 0,
    clk_sd_dist_hq INT DEFAULT 0,
    clk_sd_dist_1 INT DEFAULT 0,
    clk_sd_dist_2 INT DEFAULT 0,
    clk_sd_dist_3 INT DEFAULT 0,
    clk_sd_state_hq INT DEFAULT 0,
    clk_sd_state_1 INT DEFAULT 0,
    clk_sd_state_2 INT DEFAULT 0,
    clk_sd_state_3 INT DEFAULT 0,
    clk_sd_present_hq INT DEFAULT 0,
    clk_sd_present_1 INT DEFAULT 0,
    clk_sd_present_2 INT DEFAULT 0,
    clk_sd_present_3 INT DEFAULT 0,
    
    -- ==================== ERE (Trade 22) ====================
    ere_auth INT DEFAULT 0,
    ere_hs INT DEFAULT 0,
    ere_held INT DEFAULT 0,
    ere_av INT DEFAULT 0,
    ere_dist_hq INT DEFAULT 0,
    ere_dist_1 INT DEFAULT 0,
    ere_dist_2 INT DEFAULT 0,
    ere_dist_3 INT DEFAULT 0,
    ere_state_hq INT DEFAULT 0,
    ere_state_1 INT DEFAULT 0,
    ere_state_2 INT DEFAULT 0,
    ere_state_3 INT DEFAULT 0,
    ere_present_hq INT DEFAULT 0,
    ere_present_1 INT DEFAULT 0,
    ere_present_2 INT DEFAULT 0,
    ere_present_3 INT DEFAULT 0,
    
    -- ==================== TOTAL COLUMNS ====================
    total_auth INT DEFAULT 0,
    total_hs INT DEFAULT 0,
    total_held INT DEFAULT 0,
    total_av INT DEFAULT 0,
    total_dist_hq INT DEFAULT 0,
    total_dist_1 INT DEFAULT 0,
    total_dist_2 INT DEFAULT 0,
    total_dist_3 INT DEFAULT 0,
    total_state_hq INT DEFAULT 0,
    total_state_1 INT DEFAULT 0,
    total_state_2 INT DEFAULT 0,
    total_state_3 INT DEFAULT 0,
    total_present_hq INT DEFAULT 0,
    total_present_1 INT DEFAULT 0,
    total_present_2 INT DEFAULT 0,
    total_present_3 INT DEFAULT 0,
    
    -- ==================== SYSTEM COLUMNS ====================
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    -- Indexes for performance
    INDEX idx_report_date (report_date),
    INDEX idx_created_at (created_at)
);